{{- if .Values.createtree.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ tpl (include "ctlog.createtree.fullname" $) $ }}
{{ tpl (include "common.names.namespace" $) $ | indent 2 }}
  labels:
    app.kubernetes.io/component: {{ tpl (include "ctlog.createtree.name" $) $ }}
    {{- tpl (include "common.labels.labels" $) $ | nindent 4 }}
{{- if .Values.createtree.annotations }}
  annotations:
{{ tpl (toYaml .Values.createtree.annotations) $ | indent 4 }}
{{- end }}
spec:
{{- if .Values.createtree.ttlSecondsAfterFinished }}
  ttlSecondsAfterFinished: {{ (tpl (.Values.createtree.ttlSecondsAfterFinished | toString) $) | int64 }}
{{- end }}
  template:
    spec:
      serviceAccountName: {{ tpl (include "ctlog.serviceAccountName.createtree" $) $ }}
      restartPolicy: Never
      automountServiceAccountToken: {{ tpl (.Values.createtree.serviceAccount.mountToken | toString) $ }}
      containers:
        - name: {{ tpl (include "ctlog.createtree.fullname" $) $ }}
          image: "{{ tpl (include "common.images.image" .Values.createtree.image) $ }}"
          imagePullPolicy: "{{ tpl (.Values.createtree.image.imagePullPolicy) $ }}"
          {{- tpl (include "common.images.imagePullSecrets" (dict "pullSecrets" (list .Values.createtree.image.imagePullSecrets) "context" $)) $ | indent 10 }}
          env:
          - name: NAMESPACE
            valueFrom:  
              fieldRef:
                fieldPath: metadata.namespace
          {{- if .Values.createtree.extraEnvVars }}
{{ tpl (toYaml .Values.createtree.extraEnvVars) . | indent 12 }}
          {{- end }}
          {{- if or .Values.createtree.extraEnvVarsCM .Values.createtree.extraEnvVarsSecret }}
          envFrom:
          {{- if .Values.createtree.extraEnvVarsCM }}
            - configMapRef:
               name: {{ tpl (.Values.createtree.extraEnvVarsCM) $ }}
          {{- end }}
          {{- if .Values.createtree.extraEnvVarsSecret }}
            - secretRef:
               name: {{ tpl (.Values.createtree.extraEnvVarsSecret) $ }}
          {{- end }}
          {{- end }}
          args: [
            "--namespace=$(NAMESPACE)",
            "--configmap={{ tpl (include "ctlog.config" $) $ }}",
            "--display_name={{ tpl (.Values.createtree.displayName) $ }}",
            "--admin_server={{ tpl (.Values.trillian.logServer.name) $ }}.{{ tpl (.Values.trillian.namespace.name) $ }}:{{ tpl (.Values.trillian.logServer.portRPC | toString) $}}"
          ]
    {{- if .Values.createtree.resources }}
          resources:
{{ tpl (toYaml .Values.createtree.resources) . | indent 12 }}
    {{- end }}
    {{- if .Values.createtree.containerSecurityContext }}
          securityContext:
{{ tpl (omit .Values.createtree.containerSecurityContext "enabled" | toYaml) . | indent 12 }}
    {{- end }}
          {{- if .Values.createtree.extraVolumeMounts }}
{{ tpl (toYaml .Values.createtree.extraVolumeMounts) . | indent 12 }}
          {{- end }}
    {{- if .Values.createtree.podSecurityContext }}
      securityContext:
{{ tpl (omit .Values.createtree.podSecurityContext "enabled" | toYaml) . | indent 8 }}
    {{- end }}
    {{- if .Values.createtree.tolerations }}
      tolerations:
{{ tpl (toYaml .Values.createtree.tolerations) . | indent 8 }}
    {{- end }}
    {{- if .Values.createtree.nodeSelector }}
      tolerations:
{{ tpl (toYaml .Values.createtree.nodeSelector) . | indent 8 }}
    {{- end }}
    {{- if .Values.createtree.extraVolumes }}
{{ tpl (toYaml .Values.createtree.extraVolumes) . | indent 8 }}
    {{- end }}
{{- end }}
