{{- if and .Values.createctconfig.enabled .Values.createctconfig.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "ctlog.serviceAccountName.createctconfig" . }}
{{ include "common.names.namespace" . | indent 2 }}
  labels:
    app.kubernetes.io/component: {{ include "ctlog.createctconfig.name" . }}
    {{- include "common.labels.labels" . | nindent 4 }}
  annotations:
{{ toYaml .Values.createctconfig.serviceAccount.annotations | indent 4 }}
{{- end }}
