{{- if .Values.server.service.backendConfig }}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ .Values.server.service.backendConfig.name }}
  labels:
    {{- include "common.labels.labels" $ | nindent 4 }}
{{ include "common.names.namespace" $ | indent 2 }}
spec:
{{ toYaml .Values.server.service.backendConfig.spec | indent 2 }}
---
{{- end }}