{{- if .Values.server.ingress.enabled }}
apiVersion: "networking.k8s.io/v1"
kind: Ingress
metadata:
  labels:
    {{- tpl (include "common.labels.labels" $) $ | nindent 4 }}
  name: {{ tpl (include "common.names.fullname" $) $ }}
{{ tpl (include "common.names.namespace" $) $ | indent 2 }}
  annotations:
{{ tpl (toYaml .Values.server.ingress.annotations) $ | indent 4 }}
spec:
{{- if .Values.server.ingress.className }}
  ingressClassName: {{ tpl (.Values.server.ingress.className) $ }}
{{- end }}
  rules:
    {{- range .Values.server.ingress.hosts }}
    - host: {{ required "An Ingress hostname is required" (tpl (.host) $) | quote }}
      http:
        paths:
          - path: {{ .path }}
            pathType: {{ tpl (default "Prefix" .pathType) $ }}
            backend: {{- tpl (include "common.network.ingress.backend" (dict "global" $ "context" . "port" $.Values.server.portHTTP )) $ | nindent 14 }}
    {{- end }}
{{- if .Values.server.ingress.tls }}
  tls:
    {{- range .Values.server.ingress.tls }}
    - hosts:
      {{- range .hosts }}
      - {{ (tpl (.) $) | quote }}
      {{- end }}
      secretName: {{ tpl (.secretName) $ }}
    {{- end }}
{{- end -}}
{{- end }}
{{- range .Values.server.ingresses }}
{{- if .enabled }}
---
apiVersion: "networking.k8s.io/v1"
kind: Ingress
metadata:
  labels:
    {{- tpl (include "common.labels.labels" $) $ | nindent 4 }}
  name: {{ tpl (include "common.names.fullname" $) $ }}-{{ tpl (.name) . }}
{{ tpl (include "common.names.namespace" $) $ | indent 2 }}
  annotations:
{{- if eq .className "gce"}}
    kubernetes.io/ingress.class: "gce"
    {{- if .frontendConfigSpec }}
    networking.gke.io/v1beta1.FrontendConfig: "{{ tpl (include "common.names.fullname" $) $ }}-{{ tpl (.name) . }}"
    {{- end }}
    {{- if .staticGlobalIP }}
    kubernetes.io/ingress.global-static-ip-name: {{ tpl (.staticGlobalIP) $ | quote }}
    {{- end }}
{{- end }}
{{- with .annotations }}
{{ tpl (toYaml .) $ | indent 4 }}
{{- end }}
spec:
{{- if and (.className) (not (eq .className "gce")) }}
  ingressClassName: {{ tpl (.className) $ }}
{{- end }}
  rules:
    {{- range .hosts }}
    - host: {{ required "An Ingress hostname is required" (tpl (.host) $) | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ tpl (.path) $ }}
            pathType: {{ tpl (default "Prefix" .pathType) $ }}
            backend: {{- tpl (include "common.network.ingress.backend" (dict "global" $ "context" . "port" $.Values.server.portHTTP )) $ | nindent 14 }}
        {{- end }}
    {{- end }}
{{- if .tls }}
  tls:
    {{- range .tls }}
    - hosts:
      {{- range .hosts }}
      - {{ tpl (.) $ | quote }}
      {{- end }}
      secretName: {{ tpl (.secretName) $ }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}