{{- range .Values.server.ingresses }}
{{- if and (.enabled) (eq .className "gce") (.frontendConfigSpec) }}
apiVersion: "networking.gke.io/v1beta1"
kind: FrontendConfig
metadata:
  name: {{ tpl (include "common.names.fullname" $) $ -}}-{{- .name }}
  labels:
    {{- tpl (include "common.labels.labels" $) $ | nindent 4 }}
{{ tpl (include "common.names.namespace" $) $ | indent 2 }}
spec:
{{ tpl (toYaml .frontendConfigSpec) $ | indent 2 }}
---
{{- end }}
{{- end }}
