apiVersion: v1
kind: Service
metadata:
  annotations:
{{- $port := include "rekor.server.port" . -}}
{{- $backendConfigName := include "rekor.server.fullname" . -}}
{{ if .Values.server.service.annotations }}
{{ toYaml .Values.server.service.annotations | indent 4 }}
{{ end }}
{{- range .Values.server.ingresses }}
{{- if and (.enabled) (eq .className "gce") }}
  {{- if .backendConfigSpec }}
    cloud.google.com/backend-config: '{"ports": {"{{- printf "%v" $port -}}": "{{- printf "%v-%v" $backendConfigName .name -}}"}}'
  {{- end }}
    cloud.google.com/neg: '{"ingress": true}'
{{- break -}}
{{- end }}
{{- end }}
  labels:
    {{- include "rekor.server.labels" . | nindent 4 }}
{{- if .Values.server.service.labels }}
{{ toYaml .Values.server.service.labels | indent 4 }}
{{- end }}
  name: {{ template "rekor.server.fullname" . }}
{{ include "rekor.namespace" . | indent 2 }}
spec:
  ports:
    {{- tpl (toYaml .Values.server.service.ports) . | nindent 4 }}
  selector:
    {{- include "rekor.server.matchLabels" . | nindent 4 }}
  type: "{{ .Values.server.service.type }}"
